// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        return web;
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo2cbhtxejH5swdO_XwgTvOsFPFF5jeCI',
    appId: '1:367004069452:web:6dd08591758ed637a04ee9',
    messagingSenderId: '367004069452',
    projectId: 'reserva-ja-app',
    authDomain: 'reserva-ja-app.firebaseapp.com',
    databaseURL: 'https://reserva-ja-app-default-rtdb.firebaseio.com',
    storageBucket: 'reserva-ja-app.firebasestorage.app',
    measurementId: 'G-C1LRW0GK0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtZAThxxEpMaoic4CdOKjcbVgawWNOvzU',
    appId: '1:367004069452:android:d25c04be78c4a5bca04ee9',
    messagingSenderId: '367004069452',
    projectId: 'reserva-ja-app',
    databaseURL: 'https://reserva-ja-app-default-rtdb.firebaseio.com',
    storageBucket: 'reserva-ja-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuGHwqZ5f2ulUXkaN8DvKuhbLnqNbueeE',
    appId: '1:367004069452:ios:bb0acf1bd4909eaca04ee9',
    messagingSenderId: '367004069452',
    projectId: 'reserva-ja-app',
    databaseURL: 'https://reserva-ja-app-default-rtdb.firebaseio.com',
    storageBucket: 'reserva-ja-app.firebasestorage.app',
    iosBundleId: 'com.example.reservaJa',
  );
}
