// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

String get databaseUrl => dotenv.env['DATABASE_URL'] ?? '';
String get projectId => dotenv.env['PROJECT_ID'] ?? '';
String get bucket => dotenv.env['BUCKET'] ?? '';

String get androidApiKey => dotenv.env['ANDROID_API_KEY'] ?? '';
String get iosApiKey => dotenv.env['IOS_API_KEY'] ?? '';
String get webApiKey => dotenv.env['WEB_API_KEY'] ?? '';

String get androidAppId => dotenv.env['ANDROID_APP_ID'] ?? '';
String get iosAppId => dotenv.env['IOS_APP_ID'] ?? '';
String get webAppId => dotenv.env['WEB_APP_ID'] ?? '';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: webApiKey,
    appId: webAppId,
    messagingSenderId: '367004069452',
    projectId: projectId,
    authDomain: 'reserva-ja-app.firebaseapp.com',
    databaseURL: databaseUrl,
    storageBucket: bucket,
    measurementId: 'G-C1LRW0GK0X',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: androidApiKey,
    appId: androidAppId,
    messagingSenderId: '367004069452',
    projectId: projectId,
    databaseURL: databaseUrl,
    storageBucket: bucket,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: iosApiKey,
    appId: iosAppId,
    messagingSenderId: '367004069452',
    projectId: projectId,
    databaseURL: databaseUrl,
    storageBucket: bucket,
    iosBundleId: 'com.example.reservaJa',
  );
}
